// CLI: npm run house:transcript -- [--frame free|adalian] [--sovereign id] [--seed N] [--sex male|female] [--mahaut] [--save file.koad] [--out file]
// Plays the Founder opening's prologue and Book I, Act I by a fixed route (the first open choice where the route says
// nothing) and writes what the player reads as Markdown: for the author's read and playtest notes.
import { readFileSync, writeFileSync } from 'node:fs';
import { decodeDynasty } from '@dynasty/contract';
import { loadContent } from './content-loader';
import { newGame, view, choose } from '../src/game/index';
import type { Frame } from '../src/content/schema';
import { renderText } from '@engine/text';
import { fromDynasty } from '../src/game/import';
import { toDynasty } from '../../knight/src/game/dynasty';
import { loadPlans, playPlan } from '../../knight/tools/bot-lib';
import { loadContent as loadKnight } from '../../knight/tools/content-loader';

const args = process.argv.slice(2);
const opt = (k: string) => { const i = args.indexOf(`--${k}`); return i >= 0 ? args[i + 1] : undefined; };
const frame = (opt('frame') ?? 'free') as Frame;
const content = loadContent();
// --mahaut: the crowned path, from a Knight of Adalia crowned life married to Mahaut with no children before her
function crownedWithMahaut(seed: number) {
  const knight = loadKnight();
  const plan = loadPlans().find((p) => playPlan(knight, p).state.ended?.ending === 'crowned')!;
  const base = toDynasty(playPlan(knight, plan).state, knight);
  return fromDynasty(content, { ...base, flags: [...base.flags, 'c5_married_mahaut'], spouse: { id: 'mahaut_armance', name: "Mahaut d'Armance", alive: true }, heirs: [] }, { seed });
}
const route: Record<string, string> = {
  h_p01_hall: 'bounds', h_p02_company: 'counsel', h_p03_heir: 'manor', h_p04_suit: 'law', h_p05_michaelmas: 'pay',
  h_p06_offer: 'ask', h_p06_request: 'let_go', h_p07_year: 'mass', h_p08_summons: 'ride', h_p08_estates: 'women', h_p08_election: 'queen',
  h_p08_patent: 'defend', h_p09_illness: 'physician', h_p10_handover: 'hall', h_p11_first_days: 'change', h_p12_will: 'amend',
  h_p13_boundary: 'ride', h_p14_deathbed: 'be_myself', h_p15_funeral: 'chancel', h_p16_oath: 'reserve',
  h_b01_homage: 'ask', h_b01_withholder: 'hold', h_b02_herald: 'women', h_b02_governor: 'stand', h_b03_router: 'go_on',
  h_b03_match: 'kerguen', h_b03_sauvel: 'warm', h_b04_wedding: 'rank', h_b06_suit: 'argue', h_b07_grievance: 'manor',
  h_b08_match: 'choose', h_b08_visit: 'inside', h_b09_abbot: 'read', h_b10_knights: 'pension', h_b12_estates: 'end',
  h_pc00_crown: 'go_on', h_pc01_court: 'ride', h_pc02_company: 'counsel', h_pc03_heir: 'mahaut', h_pc04_querec: 'demand',
  h_pc05_exchequer: 'largesse', h_pc06_embassy: 'free', h_pc08_estates: 'swear', h_pc09_illness: 'rest', h_pc10_crowning: 'cathedral',
  h_pc11_council: 'speak', h_pc12_regency: 'both', h_pc13_rising: 'march', h_pc14_question: 'be_myself', h_pc15_bishop: 'anselm',
  h_pc16_acclamation: 'own', h_bc01_homage: 'refuse', h_bc02_claim: 'hear', h_bc03_betrothal: 'tanguy', h_bc04_court: 'stand',
  h_bc05_querec: 'hostage', h_bc06_sibling: 'close', h_bc07_mother: 'vote', h_bc08_household: 'own', h_bc09_estates: 'end',
};
// --save: a real Knight of Adalia export (a KOAD1 code in a file)
const save = opt('save');
let s = save ? fromDynasty(content, await decodeDynasty(readFileSync(save, 'utf8').trim()), { seed: Number(opt('seed') ?? 11) }) : opt('mahaut') !== undefined ? crownedWithMahaut(Number(opt('seed') ?? 11)) : newGame(content, { opening: 'founder', frame, sovereign: opt('sovereign'), seed: Number(opt('seed') ?? 11), name: opt('name') ?? 'Hal Fletcher', sex: (opt('sex') ?? 'male') as 'male' | 'female' });
const out: string[] = [`# House of Adalia: the prologue and Book I, Act I, as played (${content.registry.frames[frame]!.label}, under ${renderText('{realm.sovereign}', s, content)})`, '', `${save ? `Imported from the Knight of Adalia save in ${save}` : opt('mahaut') !== undefined ? 'Crowned opening, a Knight of Adalia crowned life married to Mahaut' : 'Founder opening, fresh start'}, seed ${opt('seed') ?? 11}. Generated by \`npm run house:transcript\`; the route is in games/house/tools/transcript.ts.`, ''];
for (let i = 0; i < 200 && !s.ended; i++) {
  const v = view(content, s);
  if (v.card) out.push(`---`, '', `## ${v.card.title}${v.card.subtitle ? `: ${v.card.subtitle}` : ''}`, v.card.epigraph ? `\n> ${v.card.epigraph}\n` : '');
  out.push(`### ${v.title ?? v.sceneId}`, '', `*${v.date}*`, '', v.text.trim(), '');
  const open = v.choices.filter((c) => c.available);
  for (const c of v.choices) out.push(`- ${c.available ? '' : '~~'}${c.text}${c.available ? '' : `~~ (${c.lockReason})`}${c.band ? ` [${c.band}]` : ''}`);
  const pick = open.find((c) => c.id === route[v.sceneId]) ?? open[0]!;
  out.push('', `**You choose:** ${pick.text}`, '');
  s = choose(content, s, pick.id).state;
  const o = view(content, s).outcome;
  if (o?.text) out.push(o.text.trim(), '');
  if (o?.changes?.length) out.push(`*${o.changes.join('; ')}*`, '');
}
const end = view(content, s);
out.push(`### ${end.title ?? 'The End'}`, '', end.text.trim(), '');
const file = opt('out');
if (file) writeFileSync(file, out.join('\n')); else console.log(out.join('\n'));
