// CLI: npm run house:transcript -- [--frame free|adalian] [--sovereign id] [--seed N] [--sex male|female] [--out file]
// Plays the Founder opening's prologue by a fixed route (the first open choice where the route says
// nothing) and writes what the player reads as Markdown: for the author's read and playtest notes.
import { writeFileSync } from 'node:fs';
import { loadContent } from './content-loader';
import { newGame, view, choose } from '../src/game/index';
import type { Frame } from '../src/content/schema';
import { renderText } from '@engine/text';

const args = process.argv.slice(2);
const opt = (k: string) => { const i = args.indexOf(`--${k}`); return i >= 0 ? args[i + 1] : undefined; };
const frame = (opt('frame') ?? 'free') as Frame;
const content = loadContent();
const route: Record<string, string> = {
  h_p01_hall: 'bounds', h_p02_company: 'counsel', h_p03_heir: 'manor', h_p04_suit: 'law', h_p05_michaelmas: 'pay',
  h_p06_offer: 'ask', h_p06_request: 'let_go', h_p07_year: 'mass', h_p08_summons: 'ride', h_p08_estates: 'women', h_p08_election: 'queen',
  h_p08_patent: 'defend', h_p09_illness: 'physician', h_p10_handover: 'hall', h_p11_first_days: 'change', h_p12_will: 'amend',
  h_p13_boundary: 'ride', h_p14_deathbed: 'be_myself', h_p15_funeral: 'chancel', h_p16_oath: 'reserve',
};
let s = newGame(content, { opening: 'founder', frame, sovereign: opt('sovereign'), seed: Number(opt('seed') ?? 11), name: opt('name') ?? 'Hal Fletcher', sex: (opt('sex') ?? 'male') as 'male' | 'female' });
const out: string[] = [`# House of Adalia: the prologue, as played (${content.registry.frames[frame]!.label}, under ${renderText('{realm.sovereign}', s, content)})`, '', `Founder opening, fresh start, seed ${opt('seed') ?? 11}. Generated by \`npm run house:transcript\`; the route is in games/house/tools/transcript.ts.`, ''];
for (let i = 0; i < 200 && !s.ended; i++) {
  const v = view(content, s);
  if (v.card) out.push(`---`, '', `## ${v.card.title}${v.card.subtitle ? `: ${v.card.subtitle}` : ''}`, v.card.epigraph ? `\n> ${v.card.epigraph}\n` : '');
  out.push(`### ${v.title ?? v.sceneId}`, '', `*${v.date}*`, '', v.text.trim(), '');
  const open = v.choices.filter((c) => c.available);
  for (const c of v.choices) out.push(`- ${c.available ? '' : '~~'}${c.text}${c.available ? '' : `~~ (${c.lockReason})`}${c.band ? ` [${c.band}]` : ''}`);
  const pick = open.find((c) => c.id === route[v.sceneId]) ?? open[0]!;
  out.push('', `**You choose:** ${pick.text}`, '');
  s = choose(content, s, pick.id).state;
  const o = view(content, s).outcome;
  if (o?.text) out.push(o.text.trim(), '');
  if (o?.changes?.length) out.push(`*${o.changes.join('; ')}*`, '');
}
const end = view(content, s);
out.push(`### ${end.title ?? 'The End'}`, '', end.text.trim(), '');
const file = opt('out');
if (file) writeFileSync(file, out.join('\n')); else console.log(out.join('\n'));
