// Generates a scripted plan from a bot run: searches seeds and policies for a
// run that ends as wanted and meets the given conditions, then records every
// scene's choice and check result so the run replays exactly.
//
// Usage:
//   npx tsx tools/make-plan.ts --name "The Usurper" --file 05-usurper --bg burgess \
//     --ending crowned [--want "flag.c2_granted_kerval"] [--want ...] [--expect ...]
//   npx tsx tools/make-plan.ts --regen      re-records every generated plan in tools/plans
//
// Generated plans carry a `generated` block (policy, seed, wants) so that a
// content change which breaks one can be fixed by --regen rather than by hand.
import { writeFileSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import YAML from 'yaml';
import { loadContent } from './content-loader';
import { playOnce, DEFAULT_POLICIES, policyName, PLAN_DIR, playPlan, type Plan, type Policy } from './bot-lib';
import { newGame, choose } from '../src/engine/index';
import { test as testCond } from '../src/engine/conditions';
import type { ContentBundle } from '../src/content/schema';
import type { GameState } from '../src/engine/state';

interface Spec { name: string; file: string; background: string; ending: string; want: string[]; expect: string[]; note?: string }
interface Generated { policy: string; seed: number; want: string[] }

function finalState(content: ContentBundle, bg: string, seed: number, path: string[]): GameState {
  let s = newGame(content, { background: bg, seed, name: 'Bot' });
  for (const p of path) s = choose(content, s, p.split('/')[1]!).state;
  return s;
}

/**
 * Replays a bot path and records "scene: choice!result". A scene visited more than once
 * (a shop, which loops on itself) records the list of its choices in order.
 */
function record(content: ContentBundle, bg: string, seed: number, path: string[]): Record<string, string | string[]> | null {
  let s = newGame(content, { background: bg, seed, name: 'Plan' });
  const visits: Record<string, string[]> = {};
  for (const p of path) {
    const [scene, id] = p.split('/') as [string, string];
    const r = choose(content, s, id);
    (visits[scene] ??= []).push(r.check ? `${id}!${r.check.result}` : id);
    s = r.state;
  }
  return Object.fromEntries(Object.entries(visits).map(([k, v]) => [k, v.length === 1 || v.every((x) => x === v[0]) ? v[0]! : v]));
}

function find(content: ContentBundle, spec: Spec, start = 1, limit = 4000): { policy: Policy; seed: number; steps: Record<string, string | string[]> } | null {
  for (let i = start; i < start + limit; i++) {
    const policy = DEFAULT_POLICIES[i % DEFAULT_POLICIES.length]!;
    const seed = 1000 + i * 37;
    const r = playOnce(content, spec.background, seed, policy, 3000);
    if (r.outcome !== 'ending' || r.ending !== spec.ending) continue;
    const s = finalState(content, spec.background, seed, r.path);
    if (!spec.want.every((w) => testCond(w, s, content))) continue;
    const steps = record(content, spec.background, seed, r.path);
    if (!steps) continue;
    const plan: Plan = { name: spec.name, background: spec.background, seed, steps, ending: spec.ending, expect: [...spec.want, ...spec.expect] };
    if (!playPlan(content, plan).ok) continue;
    return { policy, seed, steps };
  }
  return null;
}

function write(spec: Spec, found: { policy: Policy; seed: number; steps: Record<string, string | string[]> }) {
  const gen: Generated = { policy: policyName(found.policy), seed: found.seed, want: spec.want };
  const doc = {
    name: spec.name,
    background: spec.background,
    seed: found.seed,
    generated: gen,
    steps: found.steps,
    ending: spec.ending,
    expect: [...spec.want, ...spec.expect],
  };
  const head = `# ${spec.name}: generated by tools/make-plan.ts from a bot run (${gen.policy}).\n# ${spec.note ?? ''}\n# Regenerate with: npx tsx tools/make-plan.ts --regen\n`;
  writeFileSync(join(PLAN_DIR, `${spec.file}.yaml`), head + YAML.stringify(doc, { lineWidth: 0 }));
}

const args = process.argv.slice(2);
const content = loadContent();
const many = (flag: string) => args.flatMap((a, i) => (a === flag ? [args[i + 1]!] : []));
const one = (flag: string) => many(flag)[0];

if (args.includes('--regen')) {
  for (const f of readdirSync(PLAN_DIR).filter((f) => f.endsWith('.yaml'))) {
    const raw = YAML.parse(readFileSync(join(PLAN_DIR, f), 'utf8')) as Plan & { generated?: Generated };
    if (!raw.generated) continue;
    const want = raw.generated.want;
    const spec: Spec = { name: raw.name, file: f.replace(/\.yaml$/, ''), background: raw.background, ending: raw.ending, want, expect: raw.expect.filter((e) => !want.includes(e)) };
    const found = find(content, spec);
    if (!found) { console.log(`FAILED to regenerate ${f}`); process.exitCode = 1; continue; }
    write(spec, found);
    console.log(`regenerated ${f} (seed ${found.seed})`);
  }
} else {
  const spec: Spec = { name: one('--name')!, file: one('--file')!, background: one('--bg')!, ending: one('--ending')!, want: many('--want'), expect: many('--expect'), note: one('--note') };
  const found = find(content, spec);
  if (!found) { console.log('no run found'); process.exit(1); }
  write(spec, found);
  console.log(`wrote ${spec.file}.yaml (seed ${found.seed}, ${Object.keys(found.steps).length} steps)`);
}
